import Head from 'next/head'
import { apiRequest } from '@my-app/contentful-client';

export async function getStaticProps() {
  const data = await apiRequest();
  return {
    props: {
      data
    }
  }
}

export default function Home({ data }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{data}</h1>
      </main>
    </>
  )
}
